services:
  db:
    image: postgres:17
    container_name: bankapp_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: bankapp_backend
    restart: always
    env_file: .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db

volumes:
  postgres_data:
